### ISSUE TITLE
How to convert code to jsonl format?

### ISSUE THREAD

**Issue by mkravchik** [dcoimbra/dx2021#1]
Hi,
I'd like to run tests with code2vec on additional C/Cpp datasets, but do not know how to convert the code into the jsonl format you use. Could you recommend one?
Thanks a lot!

**Comment by dcoimbra** [comment]
Hi, I'm sorry that it took so long to reply to this comment. This is really only a replication package and I don't ever look at this repository or maintain it...

The dataset was obtained in json format from Microsoft: https://drive.google.com/file/d/1x6hoF7G-tSYxg8AFybggypLZgMGDNHfF/view

I simply took each entry and put it in its own JSON object. That's how I got a JSONL format. As for converting code to JSON, you'd need a C parser to extract each function and aggregate it into a JSON object alongside a label that you provide.

I'm sorry that I can't help you further. I've left this project and academia a long time ago, this repository only really exists as a reference. Feel free to clone/fork it and expand on it any way you want!
